### PR TITLE
Spanish Translation

### PR DESCRIPTION
**Pull request by TheSoraHD**
- Fixes crash when getting Drive Gauge Up through a LvUp/Bonus Text Box!!!
- Translates all .yml files inside msg folder.
- Tells the mod.yml file to operate with the Spanish Translation only when the game is in Spanish.
- Credits added.

image
image
image

### CODE REVIEW

**Comment by 1234567890num** [comment]
There's some changes that are only done on English to preserve some continuity. If there's no such continuity problems with the vanilla Spanish texts, can you remove their edits from the files? These include:
- Antiform -> Anti Form (maybe `Forma anti` would be better? Idk Spanish but it seems more in line with the other forms' texts)
- Dodge Roll LV 1 -> Dodge Roll LV1 (no changes needed, so you can remove the edits to the sys.yml)
  - Applies to the other Dodge Roll levels too
- Limit names (idk what they're called in the Spanish translation in other games)
  - Sonic Rave -> Sonic Blade
  - Last Arcanum -> Ars Arcanum
  - Infinity -> Ragnarok
-  Cost: 4 -> Drive points consumed: 4 (Spanish translation is also consistent, so you can also remove this edit)

**Comment by 1234567890num** [comment]
`Fixes crash when getting Drive Gauge Up through a LvUp/Bonus Text Box!!!`

Also, which part of the PR does this?

**Comment by TheSoraHD** [comment]
> There's some changes that are only done on English to preserve some continuity. If there's no such continuity problems with the vanilla Spanish texts, can you remove their edits from the files? These include:

Oh, I patched all the visible text strings present in the files because they were in English in my game, but since the mod.yml is changed now they aren't necessary at all. Got it!

> * Antiform -> Anti Form (maybe `Forma anti` would be better? Idk Spanish but it seems more in line with the other forms' texts)

I'll remove it. Also, "Forma anti" is not cool, since "anti" is a prefix that changes the object to its antithesis.

> * Dodge Roll LV 1 -> Dodge Roll LV1 (no changes needed, so you can remove the edits to the sys.yml)
>   
>   * Applies to the other Dodge Roll levels too

Fabulous!

> * Limit names (idk what they're called in the Spanish translation in other games)
>   
>   * Sonic Rave -> Sonic Blade
>   * Last Arcanum -> Ars Arcanum
>   * Infinity -> Ragnarok

In the Spanish translations, there isn't such consistency, specially with KH2. So, I'll change the names to its KH1/BBS/KH3 counterparts:
* Sonic Rave -> Estocada Veloz (official is "Estocada Sónica")
* Last Arcanum -> Último Arcano (official is "Arcano")
* Infinity -> Ragnarok (official is "Infinidad")
* Strike Raid -> Tiro Mortífero (official is "Tiro Divino")

> * Cost: 4 -> Drive points consumed: 4 (Spanish translation is also consistent, so you can also remove this edit)

Yes, but there's a typo in the official release, so this will stay as it is :p


> `Fixes crash when getting Drive Gauge Up through a LvUp/Bonus Text Box!!!`
> 
> Also, which part of the PR does this?

See [Fix Drive Gauge Up Crash when playing in Spanish](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/pull/44/commits/7c23cfa4d7ac0245bc77818eed8d549774547bd2). The reason it's crashing right now is because the text is too long (before was "¡Indicador de Fusión aumentado!", but that was transformed in-game into "¡{arrow_up}¡Indicador de Fusión aumentado!!", thus causing the crash), so I changed "aumentado" by a "+1", which does the trick. =)

**Comment by 1234567890num** [comment]
> I'll remove it. Also, "Forma anti" is not cool, since "anti" is a prefix that changes the object to its antithesis.

I think having it be `Forma [something]` would be best for consistency, but I'll leave the final judgement to you. Feel free to choose `Antiforma` or `Anti-forma` if you feel either of those are better.

> Yes, but there's a typo in the official release, so this will stay as it is :p

It seems less like a typo and more like a wording/grammar issue, so I'll take your word for it.

**Comment by TheSoraHD** [comment]
> I think having it be `Forma [something]` would be best for consistency, but I'll leave the final judgement to you. Feel free to choose `Antiforma` or `Anti-forma` if you feel either of those are better.

The easiest thing to do, for now, is to leave it as it is (official).

> It seems less like a typo and more like a wording/grammar issue, so I'll take your word for it.

Also, sorry for not giving enough context before. The real problem is with the words "para usa límites", it should be "para usar límites" (r is missing, the conjugation is incorrect).

image

**Pull request merged**
